#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: tvoyJ/iv8Y+9VaKvOFvxegvQFBNqPkhiwghS8lQDsrt7B/1MWU4e8uOHQzfTU580
  NUGET_TOKEN:
    secure: P2AbVXF6ZhkWoNAFjmIhzMH3FEgJkFtXPozru7MTOWRn6HCRiq3Dz+TP36knnevg
  CODECOV_TOKEN:
    secure: p2KPNbaK5X26DvnuDHzZxrt0xT9AoQdmoqVHlfpmLuNVkzeMjiPLQUxC42TfIxnQ
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off