#------------------------------------------------------------#
#     CI Build Configuration for master branch pre-release   #
#------------------------------------------------------------#
version: "{build}"
image: Visual Studio 2019
configuration: Release
environment:
  GITHUB_TOKEN:
    secure: //RzPD6sJwALrAUPet5ffD2C82ETjhYb1XR30sWRHtqNK5E9Q9xN96GNP9OfWCwX
  NUGET_TOKEN:
    secure: 7BiuqzrHnmb8PAvTPuvyQkA7PhLFBSmBH+lof9tX9SM1DVFSQZAG6dTbVXEA+pkD
  CODECOV_TOKEN:
    secure: p2KPNbaK5X26DvnuDHzZxrt0xT9AoQdmoqVHlfpmLuNVkzeMjiPLQUxC42TfIxnQ
  APPVEYOR_TOKEN:
    secure: wVt1RgJAnhNTyIjtK9yFkQbEEM+fBk1TLUzo0j3pe2U=
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
build_script:
- ps: .\build.ps1
test: off
